### ISSUE TITLE
swap 1/4 vs started

### ISSUE THREAD

**Issue by imylomylo** [lukechilds/hyperdex-bugtracker#11]
usability wise, using the dexfee paid, bob deposit, alice payment etc. as descriptors is nicer than 1/4.  adds to education for some.

not necessarily using "bob deposit" but some other phrase.  my 2c.

now, gsad :)

**Comment by lukechilds** [comment]
I'm not sure it is. If you're not familiar with the steps and your trade is on `bobdeposit` most users will have no idea what that means or how far through it is. Everyone understands what `2/4` means.

Remember this is supposed to be grandma friendly, we're trying to be usable for technically inept users.

That said, you raise a good point about adding education. I'm currently working on the "View" modal to view more info on a swap. This will contain more detailed info such as which AS TXs you have completed and which are pending. The name, the amount, the TXID etc.

So I think this will be a good compromise of obvious data in the main UI, but more complex data in the modal for advanced users or people who want to understand what's going on.

**Comment by jansako** [comment]
It could also be done by a tooltip popping up when the user hovers over the status. 

Tooltips are great for educating users without cluttering the UI.

On a related note, maybe having a timer on the 'pending' that would tell the user how long before status will change to 'failed' (I suppose 'expired' would be more appropriate once jl implements the error codes :-)

**Comment by lukechilds** [comment]
>On a related note, maybe having a timer on the 'pending' that would tell the user how long before status will change to 'failed' (I suppose 'expired' would be more appropriate once jl implements the error codes :-)

That would be great but reliably calculating when a trade will be expired is not a simple task:

https://github.com/jl777/SuperNET/issues/745
https://github.com/jl777/SuperNET/issues/756
https://github.com/jl777/SuperNET/issues/775

**Comment by imylomylo** [comment]
Replying to your first reply re: bobdeposit.

The barterdex info screen that says, "dex fee paid, waiting for X deposit",
"seller paid deposit, waiting for buyer payment", "payment made, waiting
for seller payment"

Those were useful indicators in BarterDEX, compared to 1/4 imo.

HyperDEX knows the stage, so it's just a cosmetic thing.  How much work
would it be to make it an option in the settings for preferred view (kind
of like a language file)

Option:  Status as steps (1/4, 2/4)
Option:  Status as BarterDEX description


Cheers

**Comment by lukechilds** [comment]
The main issue is real estate, we have limited space in the swaps list on some screen sizes so we need to make sure it displays well on all screens.

Let me get the view swap modal pushed and then we can review this and see if we can make it more obvious.

**Comment by sindresorhus** [comment]
We now show the full names of the steps if you click the "View" button to see swap details.
