### ISSUE TITLE
Swaps list UI scrollbar improvement

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex-bugtracker#13]
Currently the vertical scrollbar on the swaps list clashes with the overall UI design. It also touches the edge of the 'view' button.

Suggestion:
- compress the list a bit (shift some columns to the left) to create some white space between the 'view' button and the scrollbar
- adjust the appearance of the scrollbar to fit in better with the overall design (color, rounded edges)

![image](https://user-images.githubusercontent.com/34211887/39510847-09be0556-4da0-11e8-8146-1875f7e8fec3.png)

**Comment by sindresorhus** [comment]
I agree. I plan to style the scrollbars. It has just not been a priority as both @lukechilds and I work on macOS where the default scrollbar looks nice.
