### ISSUE TITLE
Inventory screen

### ISSUE THREAD

**Issue by siulynot** [lukechilds/hyperdex-bugtracker#2]
A screen with inventory or listunspent list would be important to determine if a failed swap is due to not having correct utxo.

**Comment by lukechilds** [comment]
We ideally don't want to expose any concept of UTXOs to the user, this should all be handled by `marketmaker` without interaction from the user. I know it isn't currently but I have some ideas how it could be I want to discuss with the mmv2 team.

I'll leave this issue open for now but I don't think we'll implement this unless we absolutely have to. Grandma friendly is the goal, I don't know if you've ever tried explaining UTXOs to your Grandma, but it probably won't go well. 😉

**Comment by lukechilds** [comment]
Closing this as it's looking like we'll get transparent UTXO handling in mmv2.

You can track the issue here: https://github.com/artemii235/SuperNET/issues/47
