### ISSUE TITLE
Withdraw - "max" button should save some for fees

### ISSUE THREAD

**Issue by 11allbits** [lukechilds/hyperdex-bugtracker#20]
---

HyperDEX 0.0.0-testbuild.7
Electron 2.0.0
linux 4.13.0-41-generic
Locale: en-US

**Comment by sindresorhus** [comment]
Thanks for reporting. This is a known issue. The `max` button is currently not very useful. We intend to improve this soon.

I noticed you're on an old HyperDEX build. Get the latest build here: https://github.com/lukechilds/hyperdex-nightlies/releases

**Comment by sindresorhus** [comment]
Moved to https://github.com/lukechilds/hyperdex/issues/282
