### ISSUE TITLE
Default screen size

### ISSUE THREAD

**Issue by siulynot** [lukechilds/hyperdex-bugtracker#3]
The default screen width (at least in my laptop) was 1100... that size cut part of the app controls. I raised the size to 1200 (in /.config/HyperDEX/config.json) and it fixed the issue. 

 Maybe it would be good to add 100 pixels to default size calculation.

**Comment by lukechilds** [comment]
Yeah, we've changed the UI a lot since we set those sizes, that needs increasing, thanks 👍

**Comment by lukechilds** [comment]
Thanks for reporting, this is fixed now 🎉 

https://github.com/lukechilds/hyperdex/pull/159
