### ISSUE TITLE
size amount, adress text

### ISSUE THREAD

**Issue by IndeNodes-Company** [lukechilds/hyperdex-bugtracker#4]
Hard to see amount, adress and text error
![](https://i.imgur.com/ww3z7wr.jpg)

my resolution Pc
![](https://i.imgur.com/mzOwmUH.jpg)

**Comment by lukechilds** [comment]
What size is your monitor in inches?

**Comment by sindresorhus** [comment]
Thanks for reporting. I'm addressing this in https://github.com/lukechilds/hyperdex/pull/227
