### ISSUE TITLE
Executing New order disrupts an already ongoing swap

### ISSUE THREAD

**Issue by siulynot** [lukechilds/hyperdex-bugtracker#5]
While testing i noticed that after getting a swap matched, i can execute a new swap. This second swap goes through, but the first swap doesnt seem to finish. It gets stuck where it was. In my case, the swaps get stuck at 1/4.

If you need any other info, let me know.

**Comment by lukechilds** [comment]
Does this happen consistently and is it reproducible? It could just be a coincidence that the first trade didn't finish.

We are just passing order requests through to `marketmaker` so if this is reproducible it's a bug in mm.

**Comment by sindresorhus** [comment]
Closing for lack of response. @siulynot If this still happens, would be nice if you could open a new issue over at https://github.com/lukechilds/hyperdex with some more info :)
