### ISSUE TITLE
Improve Error Reporting

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex-bugtracker#6]
When trying to execute a trade and only having one UTXO, OR trying to sell less than 10% of a UTXO (I can't tell which cause the message is unclear :-) ),
I get a 'something unexpected happened'. 

![image](https://user-images.githubusercontent.com/34211887/39467440-fbbce1c4-4ce2-11e8-9eb5-b699adc69a69.png)

Suggestion: message should be clear on next steps.

**Comment by lukechilds** [comment]
Thanks for reporting @jansako 

The error messages are provided to us directly from `marketmaker`. We agree they are not that clear and have made attempts to make some of them more obvious.

However unfortunately we don't get any error codes, only error messages, so it's very fragile for us to try and handle these manually. If the error message text from `marketmaker` ever gets changed in the future it will break all of our error handling code.

There are also some cases where we get not error code or error message, we just have missing properties in the response and have to guess what went wrong, like in the case with this error:

```js
// TODO: Temp workaround for marketmaker issue
if (!result.pending) {
  this.setState({statusMessage: 'Something unexpected happened. Are you sure you have enough UTXO?'});
  return;
}
```

We need `marketmaker` to support error codes before we can reliably improve error handling but it is on our list to do.

More info in this issue: https://github.com/jl777/SuperNET/issues/717

Please give it a thumbs up if it's something you'd like to see fixed.

**Comment by sindresorhus** [comment]
Moved to https://github.com/lukechilds/hyperdex/issues/280
