### ISSUE TITLE
Take into account lock time after a failed trade request

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex-bugtracker#7]
I have one UTXO, try to get a trade. A trade fails (for whatever reason), but my UTXO is still locked until 'locktime' expires. When I try to executre another trade before that, I get this error:
![image](https://user-images.githubusercontent.com/34211887/39467709-4f324f46-4ce4-11e8-9194-cea00dcf8c6f.png)

Suggestion: different messages for when the UTXO is locked, from a genuine 'you don't have enough funds to execute this'

**Comment by jansako** [comment]
I suppose this is the same 'error handling' situation that needs to be fixed on MM side? 
[https://github.com/lukechilds/hyperdex-bugtracker/issues/6](url)

**Comment by lukechilds** [comment]
Yeah, will close this in favour of https://github.com/lukechilds/hyperdex-bugtracker/issues/6. Also updated the title in the other issues to "Improve Error Reporting" so it's more generic.

Thanks for reporting!

**Comment by lukechilds** [comment]
And regarding:

>Suggestion: different messages for when the UTXO is locked, from a genuine 'you don't have enough funds to execute this'

As you guessed, the message comes direct from mm so we have no way to differentiate. We need mm to have much better error reporting before we can show useful messages.
